# Site settings
title: v3n0m's official site # site title
description: >- # site description
  This site site was created inorder to help people who have no knowledge on cybersecurity! #<a href="https://github.com/piharpi" target="_blank" rel="noopener">@github</a>.
lang: en-US # default lang
timezone: Asia/Jakarta # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/v3n0m-hx0r/ # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: v3n0m # author name
  bio: >- # tell to the world
    Hello This is <strong>v3n0m</strong>, i am a student who Does Ctf once in a while and learn web app pentesting. if you are looking for some sorted ctf tools do check out <a href="https://github.com/apsdehal/awesome-ctf" target="_blank" rel="noopener">ctf-tools</a>.
  username: v3n0m # general username
  github: v3n0m-hx0r # github username
  twitter: v3n0m-hx0r # twitter username
  facebook: facebook_username # facebook username
  email: niran1470@email.com # email adress
  avatar: /assets/img/75c.png  # change with your own avatar

# URL settings
url: "https://klise.now.sh" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: false #i made it from true - false

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
